export const modules = [
    { key: "dashboard", label: "1. Dashboard Overview", icon: "dashboard" },
    {
        key: "tracking",
        label: "2. Live Tracking Map",
        icon: "my_location",
        live: true,
    },
    { key: "visits", label: "3. Visit Logs & Reports", icon: "assignment" },
    {
        key: "stores",
        label: "4. Store Directory & Approval",
        icon: "storefront",
        badge: 8,
    },
    { key: "catalog", label: "5. Product Catalog", icon: "inventory_2" },
    { key: "odoo", label: "6. Odoo Sync Monitor", icon: "sync_alt" },
    { key: "users", label: "7. User & Roles", icon: "manage_accounts" },
];

export const kpis = [
    {
        label: "Total Check-Ins Today",
        value: "318",
        suffix: "Visits",
        progress: 88.3,
        badge: "SHIFT GOAL: 360",
        trend: "+14% vs 30d pace",
        detail: "42 visits to target",
        icon: "trending_up",
    },
    {
        label: "Avg Visit Duration",
        value: "28m 45s",
        suffix: "/ store",
        progress: 34.2,
        badge: "GUIDE: 20-45m",
        trend: "Compliance Optimal",
        detail: "6 Anomaly Flags",
        icon: "schedule",
    },
];

export const clusters = [
    {
        name: "North District Sector",
        reps: 14,
        target: 110,
        completed: 96,
        percentage: 87,
    },
    {
        name: "Central District Sector",
        reps: 18,
        target: 160,
        completed: 148,
        percentage: 92,
    },
    {
        name: "South District Sector",
        reps: 10,
        target: 90,
        completed: 74,
        percentage: 82,
    },
];

export const telemetryFeed = [
    {
        name: "Marcus Vance",
        id: "#REP-092 (North)",
        avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuB2TzbFCj22Zk2etEGX3xAhSNopGS8DyGfRNtERSY5kqWOSQDul8l8p8OOtGKikpcVlSY8mLzMy9C2kxNtf6E-HQvp18SlEmLwAuZvm9cUGUfEkJ3mdOwtqiXDGLxOJeynXGM5R41oshXuNiSditWHSvxSakBhqy8AwDuSUS-9RX6XLlpz3mklUWHpGGG1X7RZaKNc9sF51YV0B3JM47ygIUSfWrRuyb5PQVGF9fJ1QGfozOnceFoA_/",
        store: "Metro Supermarket #142",
        location: "Grand Ave & 14th St",
        time: "13:42:19 EST",
        proximity: "14m Valid (Geofence Pass)",
        status: "valid",
        visit: "Visit 8 of 10",
        evidenceIcon: "photo_camera",
        evidence: "CDN Store Photo",
    },
    {
        name: "Elena Rostova",
        id: "#REP-104 (Central)",
        avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBaBNPtfLJEYqr8p8BF7pqdXraagO0OsieO2nTbw90ymUgyXURMhge-f2Kp1aO9rPJ_WXzPFHOr9MqP6X3NZEJslxvjinBJXxnFHfWl99e0ZH9o2FcgxwNOXcSqt-5QFyiHlRXhUSuKBVZa1pySmQAN6xiPDBl2oOno7yL6L5a6httHDEvEgGF2zwbymracSOhrQUviLnBFe6210ddjwP2vcUiQIHBw9UhsGpkCglR0rjPbgOJQyGI1/",
        store: "Apex Pharmacy Hub #09",
        location: "Oakwood Retail Corridor",
        time: "13:41:02 EST",
        proximity: "74m Warning (Boundary Offset)",
        status: "warning",
        visit: "Visit 6 of 8",
        evidenceIcon: "map",
        evidence: "Review Offset Pin",
    },
    {
        name: "Tariq Mansoor",
        id: "#REP-077 (Central)",
        avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAFj_H-ygN_Q7_6UB6kub5MBThYSWCwFj5jDnJMfiMH100rRCflTu05VPlDJJUG0Tj6dih4oMbLMD6IaXjsEFl4oTBALv3Z0HajR_xKSv7kgDvrmGKRNpxeHPOpED2kmPR2w-wcpjGfUJUO5BzlBQ5-M3E4Nf9RCWvACOs0N0xcXZ_2oa_ICsj9pdjs0Tsww_7D3LzEdmmvl8t9N-ENlLq1NBMkZfq17fu3oUATFCxXo-BAgumqGerg/",
        store: "Cornerstone Wholesale Co.",
        location: "Industrial Park Bay #4",
        time: "13:38:55 EST",
        proximity: "8m Valid (Geofence Pass)",
        status: "valid",
        visit: "Visit 9 of 9 (Target Met)",
        evidenceIcon: "receipt_long",
        evidence: "Order Proof #8921",
    },
    {
        name: "Lucas Kim",
        id: "#REP-119 (South)",
        avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBrgo7J090_TmiUWC4WA4jhR27jIUC6KfQ8oFGlSdU_su-0fLFuv509DuwbkM0Wp1kmRLDqaKcRXOuhJSdkUMBspdL75eUj1aXBuT_4BFaiYmIS4a4vHFgOJBI69uJB9QD5lWkaUKSXNds1Xpv6sJZx6Ar31jIKqrelvjl-7TeZsFU5hnj7db2C94SSlZa_IV3RP_iiUnffs9-cyanDT9g-MtV0roF5PN9yOYjaKhgC4ygBIQL9nSek/",
        store: "Sun Fresh Bodega #3",
        location: "South Terminal Boulevard",
        time: "13:35:10 EST",
        proximity: "19m Valid (Geofence Pass)",
        status: "valid",
        visit: "Visit 7 of 11",
        evidenceIcon: "photo_camera",
        evidence: "CDN Store Photo",
    },
    {
        name: "Sara Jenkins",
        id: "#REP-058 (South)",
        avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCSyaBjS9yBGd3AnPrzz6Zxivd9eWXueQqpk3PaEL_FAF2wnYbunY2dq5n1RyKE3uu2T8pWc4IYV9FsxnZHSxenif_A7MtZt2tl3YxOtTzgkSQLICzjulEaDLUQqhzR1EDWdEZ5a8915k2bCrGf81yxnsXcAJHVw-Khj_pzCwCHzKt-eEhBguCoYM2nUNP6rvYUkXZH_00JZL1HoVwCPQLzRmEkqmP1XvNbuKu9d0Vsb3m5_PxGMdut/",
        store: "Heritage Organic Mart",
        location: "Pinecrest Plaza Suite 12",
        time: "13:31:48 EST",
        proximity: "6m Valid (Geofence Pass)",
        status: "valid",
        visit: "Visit 8 of 10",
        evidenceIcon: "photo_camera",
        evidence: "CDN Store Photo",
    },
];

export const products = [
    {
        category: "Beverage",
        sku: "#8942",
        name: "Sparkling Citrus 24pk",
        stock: "8,400",
        price: "$24.50 / ctn",
        status: "IN STOCK",
        statusType: "success",
    },
    {
        category: "Snacks",
        sku: "#3108",
        name: "Artisan Sea Salt Chips",
        stock: "1,120",
        price: "$18.20 / ctn",
        status: "IN STOCK",
        statusType: "success",
    },
    {
        category: "Dairy",
        sku: "#5512",
        name: "Organic Almond Milk 12pk",
        stock: "240",
        price: "$31.00 / ctn",
        status: "LOW STOCK",
        statusType: "warning",
    },
    {
        category: "Confectionery",
        sku: "#9011",
        name: "Dark Cacao Bars 48ct",
        stock: "4,950",
        price: "$42.80 / ctn",
        status: "IN STOCK",
        statusType: "success",
    },
];

export const stores = [
    {
        name: "Westside Mart & Deli",
        submitted: "Submitted by Marcus Vance · 12m ago",
        gps: "GPS: 41.8819° N, 87.6321° W (Offset 82m)",
        gpsType: "warning",
        icon: "store",
    },
    {
        name: "Highland Express Liquors",
        submitted: "Submitted by Elena Rostova · 28m ago",
        gps: "GPS: 41.8722° N, 87.6401° W (Offset 11m)",
        gpsType: "success",
        icon: "local_convenience_store",
    },
];
